NODE_TYPE_UNKNOWN='NODE_TYPE_UNKNOWN'
NODE_TYPE_DB='NODE_TYPE_DB'
NODE_TYPE_DB_REPORT='NODE_TYPE_DB_REPORT'
NODE_TYPE_ACCESS='NODE_TYPE_ACCESS'
NODE_TYPE_MONITOR='NODE_TYPE_MONITOR'

NODE_TYPE=[NODE_TYPE_UNKNOWN,NODE_TYPE_DB,NODE_TYPE_ACCESS,NODE_TYPE_MONITOR]

NODE_NAME={NODE_TYPE_DB:'dbnode2'}

ALGORITHM_ROUNDROBIN='ALGORITHM_ROUNDROBIN'

ALGORITHM_DEFAULT=ALGORITHM_ROUNDROBIN


